# Generated by Django 4.2.1 on 2023-05-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='creditos',
            new_name='existencias',
        ),
    ]
